<a href="https://colab.research.google.com/github/jemayne/Numeth/blob/main/Python_Exercise_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

$$
A = \begin{bmatrix} -5, 0\\ 4, 1\end{bmatrix},
B = \begin{bmatrix} 6, -3\\ 2, 3\end{bmatrix}\\ $$


In [18]:
import numpy as np

A = np.array([[-5, 0],
             [4, 1]])
B = np.array([[6, -3],
             [2, 3]])

In [19]:
sum = A + B
print("A + B = \n", sum)

A + B = 
 [[ 1 -3]
 [ 6  4]]


In [20]:
difference1 = B - A
print("B - A = \n", difference1)

B - A = 
 [[11 -3]
 [-2  2]]


In [21]:
difference2 = A - B
print("A - B = \n", difference2)

A - B = 
 [[-11   3]
 [  2  -2]]
