<a href="https://colab.research.google.com/github/jemayne/Numerical_Methods/blob/main/Python_Exercise_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Determinants of Matrix
##using numpy.linalg.det

In [1]:
import numpy as np

In [5]:
A = np.array([[1, 2, -1], [4, 6, -2], [-1, 3, 3]])
print(A)

[[ 1  2 -1]
 [ 4  6 -2]
 [-1  3  3]]


In [9]:
print(int(np.linalg.det(A)))

-13


In [10]:
print(round(np.linalg.det(A)))

-14
